config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => "homes#about", as:'about'
  root to: 'homes#top'
  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show,:create, :index, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,  length: {maximum: 200}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path),filename: 'default_image.jpg',content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: {:message =>"使用できません"}, length: { in: 2..20 }
  validates :introduction,  length: {maximum:50}


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path),filename: 'default_image.jpg',content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      user_path(current_user.id)
    end

    def after_sign_out_path_for(resource)
      root_path
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(books_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book),notice:"You have created book successfully."
    else
      flash.now[:alert] ="book was not created because of an error"
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book= Book.new
    @books= Book.all
    @user= current_user

  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @books_user = @books.user
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    unless @user.id == current_user.id
      redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(books_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      flash.now[:alert] = "book was not updated due to an error"
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

    private

    def books_params
      params.require(:book).permit(:title, :body, :profile_image )
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def destroy
    @book = book.find(params[:id])
    @book.destroy
    redirect_to book_path
  end

  def index
    @book = Book.new
    @user = current_user
    @new_user= User.new
    @users= User.all
  end

  def create
    @book = Book.new(books_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice:"You have created book successfully."
    else
      flash.now[:alert] ="book was not created because of an error"
      render :show
    end
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(users_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      flash.now[:alert] = "user was not updated due to an error"
      render :edit
    end
  end

    private

  def users_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= flash[:notice] %><br>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class= "row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>
        <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for ="book_title">Title</label>
          <%= f.text_field :title, auotfocus: true, id: "book_Title" %>
        </div>
        <div class="form-group">
          <label for ="book_Opinion">Opinion</label>
          <%= f.text_field :body, auotfocus: true, id: "book_Opinion" %>
        </div>
          <%= f.submit "Update Book", class: "btn btn-success btn-sm" %>
        <% end %>

      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= flash[:notice] %><br>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/list', user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

      <% @books.each do |book| %>
        <tbody>
          <tr>
            <td><%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
            </td>

            <td><%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
            </td>
            <td><%= book.body %></td>
            <td colspan="3"></td>
          </tr>
        </tbody>
       <% end %>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<%= flash[:notice] %><br>

<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/list', user: @books_user ,book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class= "table">
      <tbody>
        <tr>
        <td>
          <%= link_to user_path(@books.user) do %>
            <%= image_tag @books.user.get_profile_image(100,100) %><br>
          <% end %>

            <%= link_to user_path(@books.user) do %>
              <%= @books_user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(@books) do %>
            <%= @books.title %>
          <% end %>
        </td>
        <td>
          <%= @books.body %>
        </td>
        <td>
          <% if @books.user == current_user %>
          <%= link_to  edit_book_path(@books.id), class: "btn btn-success btn-sm" do %>
            Edit
          <% end %>
        </td>
        <td>
            <%=link_to "Destroy", book_path(@books) , method: :delete, class: "btn btn-danger btn-sm", "data-confirm" => "本当に削除しますか？" %>
          <% end %>
        </td>
        </tr>
      </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="mt-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %><br

<div class="container">
  <div class="row">
    <div class= "mx-auto mt-3">

      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p> you can share and exchange your opinions , inpressions , and emotions </p>
      <p>about various books!</p>

      <div class="row">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class= "navbar navbar-expand-lg  bg-dark navbar-dark" >
        <div class="container">
          <a class="navbar-brand" href="/"> Bookers </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon "></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto" >
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>
                Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i>
                Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>
                Log out
              <% end %>
            </li>
            <% else %>
             <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light'  do %>
                <i class="fas fa-user-plus"></i>
                Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%=link_to new_user_session_path, class: 'nav-link text-light'  do %>
                <i class="fas fa-sign-in-alt"></i>
                Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
    <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<div class = "col-md-3">
  <h2>User info</h2>
    <%= image_tag user.get_profile_image(100,100) %>
    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>

    <div class="row">
      <%= link_to edit_user_path(user.id) ,class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book do |f| %>
    <div class="form-group">
      <label for= "book_title">Title</label><br>
        <%= f.text_field :title %>
    </div>
    <div class= "form-group">
      <label for= "book_opinion">Opinion</label><br>
      <%= f.text_area :body %>
    </div>
    <div class= "form-group">
        <%= f.submit 'Create Book', class: "btn btn-success btn-sm" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= flash[:notice] %><br>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class ="container">
  <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
        <div class= "form-user">
          <label for ="user_name">Name</label><br>
          <%= f.text_field :name, autofocus: true, name_length:2..20%>
        </div>
        <div class= "form-user">
          <label for = "user_Image">Image</label><br>
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        <div class ="form-user">
          <lable for = "user_Introduction">Introduction</lable><br>
          <%= f.text_field :introduction ,autofocus: true %>
        </div>
        <div class="form-user">
          <%= f.submit "Update User", class: "btn btn-secondary btn-sm" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= flash[:notice] %>
<div class="container px-5 mt-3">
  <div class="row">

    <%= render 'list', user: @user , book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

      <% @users.each do |user| %>

        <tbody>
          <tr>
            <td></td>
            <td><%= image_tag user.get_profile_image(80,80) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        </tbody>
       <% end %>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %><br>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'list', user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table ">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @books.each do |book| %>
          <tbody>
          <tr>
            <td><%= link_to user_path(book.user) do %>
                  <%= image_tag @user.get_profile_image(80,80) %>
                <% end %>
            </td>
            <td><%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
            </td>
            <td><%= book.body %></td>
            <td></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>